[project]
name = "pyflightlog"
version = "0.3.0"
description = ""
authors = [{ name = "Fabian Bühler", email = "fabian.buehler@fdtk.de" }]
requires-python = ">=3.11.2, <3.13"
readme = "README.md"
dependencies = [
    "requests>=2.30.0,<3",
    "python-dateutil>=2.8.2,<3",
    "cmd2>=2.4.3,<3",
    "colorama>=0.4.6,<0.5",
    "black>=23.3.0,<24",
    "pyside6>=6.7.1,<7",
]

[project.scripts]
flog = "pyflightlog.flightlog:main"

[dependency-groups]
dev = ["pytest>=7.4.4,<8"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

